### ISSUE TITLE
Implement YCSB

### ISSUE THREAD

**Issue by hkimura** [hkimura/foedus_code#27]
Everyone else provides it. Why not.
Even simpler than TPCC, so just a copy-paste then a bit of modification.

Probably a good warming-up for a new member.

**Comment by kumagi** [comment]
[YCSB](https://github.com/brianfrankcooper/YCSB/) is written in Java, but FOEDUS is written in C++.

I think there is two options.
1. Write YCSB driver for FOEDUS(it may use [JNI](https://en.wikipedia.org/wiki/Java_Native_Interface)). It may get unnecessary overhead of JNI.
2. Write C++ client workload along with YCSB. But it can get fake result, or might not be accepted YCSB community.

**Comment by hkimura** [comment]
I meant 2. That's what everyone in this field does.

I'm not sure what you meant by "YCSB is written in Java". YCSB is a benchmark specification.
One doesn't have to use a reference implementation and we are not asking for any official approval or whatsoever.

I think I will assign this to Tianzheng as he already did it on ERMIA and probably on Shore-MT.

**Comment by hkimura** [comment]
This is done in Tianzheng's commits. We are still working on one concurrency bug, but the issue is not in YCSB code. Thus closing.
