### ISSUE TITLE
check environment(hugepagess, shamem limits, etc) on engine start-up

### ISSUE THREAD

**Issue by kumagi** [hkimura/foedus_code#39]
as @hkimura said at #31 

>> Or output unambiguous message(instead of bus error)

> This is definitely an issue. I'm thinking about a pre-screening of the environment on engine start-up.
> It checks the number of hugepages, shmem limits, etc and immediately fails with a page-full of warning messages explaining the steps the user must take.

I think it should be enabled at least debug mode(`defined NDEBUG macro`).
On production mode, I can't decide it should be enabled or not(for start-up performance).

**Comment by hkimura** [comment]
#38 implements it. Now it does several checks at startup and writes out a bit more helpful message.
We still need good documentations to set ulimit/sysctl/hugepages etc especially for permanent config.

But, I really hesitate to distribute a program that modifies limits.conf/grub.cfg/sysctl.conf.
Must be done by someone who is super-uber careful and familiar with all linux distros/versions.

**Comment by hkimura** [comment]
I think #38 addressed it
