### ISSUE TITLE
masstree manupulation without impersonate?

### ISSUE THREAD

**Issue by kumagi** [hkimura/foedus_code#90]
I'm integrating FOEDUS into MySQL storage engine.

MySQL storage interface requires fine grained manipulation.
But FOEDUS masstree provides only `impersonate` interface for manipulation.

I know FOEDUS's impersonate interface is owe to performance.
But impersonate for every storage manipulation is **too** slow and crazy hack is needed for cursor manipulation.

Is there any way to use `foedus::storage::MasstreeStorage` without impersonation?

**Comment by hkimura** [comment]
Without a thread context, there's no transactional consistency guarantee. I'm not sure whether that's what you want. Can you somehow maintain the tie between the impersonated thread and MySQL's worker?

Impersonating for each transaction is definitely not the intended use. Please don't do it.

**Comment by kumagi** [comment]
MySQL server guarantees association with transaction and context.
So I want to manipulate thread context by hand.
Context object can be properly dispatched by MySQL.

> Can you somehow maintain the tie between the impersonated thread and MySQL's worker?
For example, Do you say that implementing some FIFO between thread and worker?

**Comment by kumagi** [comment]
My experimental code is here.

But I realized that `Thread` has real `std::thread`, not only context.
This constraint is hard to use for storage user.

```cpp:
  foedus::EngineOptions options;
  // some setting for options here.

  foedus::Engine *engine = new foedus::Engine(options);
  foedus::ErrorStack ret = engine->initialize();

  foedus::storage::masstree::MasstreeMetadata *meta =
    new foedus::storage::masstree::MasstreeMetadata("mysql");
  foedus::storage::masstree::MasstreeStorage *storage =
    new foedus::storage::masstree::MasstreeStorage();
  foedus::Epoch epoch;
  engine->get_storage_manager()->create_masstree(meta, storage, &epoch);
  assert(storage->exists());

  foedus::thread::Thread t(engine, 0, 0);  // because insert_record() needs thread!
  t.initialize();  // SEGV here

  storage->insert_record(&t, "hoge", 4, "foo", 3);

  delete meta;
  delete storage;
  delete cursor;
  delete engine;
```

and **SEGV** happens at `Thread` initialization.
Because engine is `master` so that `core_memory_` for the thread is **NULL** at [here ](https://github.com/hkimura/foedus_code/blob/master/foedus-core/src/foedus/thread/thread_pimpl.cpp#L88)

**Comment by hkimura** [comment]
That's not what I'm suggesting. Please do not instantiate a Thread object in a client code.
I'm just suggesting to keep the tie between your impersonated thread and your mysql worker context.

pls email me for more discussions on this.

**Comment by kumagi** [comment]
OK, How about make `foedus::thread::Thread` constructor `private` ?
Only `thread_pool` can instantiate it (via `friend` specification).
It will helpful for users for avoiding to write harmful code like above.

**Comment by hkimura** [comment]
Please re-open it if this is still an issue.
